# Site settings
title: NauticApp
email: nauticapplication@gmail.com
url: https://github.com/nauticapp
description: "Marine Engineering Hub for engine troubleshooting assistance, maintenance schedules, and spare part inventory. NautiGuard offers a collection of marine IoT projects focusing on safety and monitoring, including Real-Time GPS Tracking and Speed, Responsive Magnetic Heading (CoG), Position, Weather Full Forecast, Compass, and Logbook with automatically updated chart data."

keywords: "Sailing Tool, GPS Tracking, Weather Forcast, Logbook and more..."
skills: "Marine Engineering Hub for engine troubleshooting assistance, maintenance schedules, and spare part inventory. NautiGuard offers a collection of marine IoT projects focusing on safety and monitoring, including Real-Time GPS Tracking and Speed, Responsive Magnetic Heading (CoG), Position, Weather Full Forecast, Compass, and Logbook with automatically updated chart data."
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: NauticApp
  location: 
  social: All-In-One Sailing Tool
  credits: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/nautic_app
 # - title: facebook
 #   url:
  - title: google-play
    url: https://play.google.com/store/apps/details?id=io.dcoldeira.nauticapp
 

# Postal address (add as many lines as necessary)
address:


# Credits content


# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

